name: Continue Config
version: 1.0.0
schema: v1

models:
  - name: minimax
    provider: openai
    model: abab6.5s-chat
    apiKey: sk-api-OgvHVQkduIT_LJw1-ciyCpUIqM0FtHb54lMw-gXdHYz_-5u8jn0zcfUYkc-XFIxJy_TbLTGvBt09_aSIDc-MyR_ZB25f6B71KtQFrYi0wcSe1mZmTBamWeY
    apiBase: https://api.minimax.chat/v1

context:
  - provider: codebase

mcpServers:
  - name: filesystem
    command: /usr/local/bin/npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "/Users/zouxianxian/IdeaProjects"

